version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - minio
    # Add a health check to ensure the service is running
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  minio:
    image: minio/minio:latest
    command: server /data
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    # Add a health check for MinIO service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  minio_data:
